services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    EzPlatform\HubSpot\Repository\EventSubscriber\:
        resource: '../../../../../lib/Repository/EventSubscriber/*'